twitter:
  twitter_api_key: 'Vhc1Yf9Ggi10FNJA7GkUFcITc'
  twitter_api_secret: 'BZVL0ctwnIFMjDUbIqRLZlhFkVkiHBkgKBoxWhBadFvyVdeBxG'

facebook:
  facebook_api_key: '651522889510000'
  facebook_api_secret: 'aea85d4fc115629b304126be927d735f'